### ISSUE TITLE
可以加上这个豆瓣租房小组吗？

### ISSUE THREAD

**Issue by Yixiaohan** [soulteary/tenant-point#8]
可以加上这个豆瓣租房小组吗？

强烈推荐，北漂者租房可选择 [北京租房真的没有中介小组](https://www.douban.com/group/625354/#topics)

点击链接，加入豆瓣租房小组：

https://www.douban.com/group/625354/#topics

**Comment by soulteary** [comment]
当然可以，给我提个pr，我合并就好。
