### ISSUE TITLE
感谢楼主分享，我也添加一点个人租房的感受

### ISSUE THREAD

**Issue by adminlinzi** [soulteary/tenant-point#9]
1. #安彼迎APP上那种临时租住也可以，比美团的便宜一些，或者直接在各种APP上找临时的，质量很一般的住宿也可以，但是价格来说，安彼迎上的，同样价格，质量明显比美团携程之类的租到的质量好。

2.  判断房东部分，如果是那种性子很急很暴躁的，建议慎重选择，因为后面这种房东很容易毁约合同；

3. 房源搜索，有个比较累的办法，公司为中心，走着三十分钟作为一个线，画一个圆，圆内找。在公司楼下找公交站，然后确认有哪几路公交，根据公交沿线住宿找。不少人选择直接坐到终点站那种租，选的人多了，就不怎么好租了。特别是济南那种地方，有的终点站的小区和公寓，还没城中村靠谱。
 还可以用租房的APP找房东直租的，强烈建议找房东直租的，中介那个是真的麻烦，除非是确实不好找房子了，也能接受多花点钱，现在良心中介不怎么多，莫名的就可以给你搞的多出来一批费用，3k可以租的，最后你掏钱就能到6k或者9k，这在济南是亲身经历过，太黑了，最后还好克制住自己了，没掏钱，要不然就入坑了。

4. 合租最容易入的坑就是和情侣租，假设是两室的，一个人和一对情侣租，常见坑人套路就是，按照房间来平摊水电气，这种在济南可是不少的坑人套路，等于你要免费帮别人分担一部分生活开支，别管你是不是真的用了。也有比较友好的情侣租，就是那种按照人头数量来分摊费用的。总之，合租最怕的就是遇到一个十分浪费水电气，然后把你拖下水多掏钱的坑人合租人。

**Comment by soulteary** [comment]
可以提个PR合并到内容中，:D
